### ISSUE TITLE
fixed docs versions?

### ISSUE THREAD

**Issue by TroyLDay** [nvd3-community/nvd3#108]
It is encouraging to see the new version of the docs take shape! 

Will there be any fixed version doc resources that can be pointed to (like a tag). 

My concern is that if I put a pointer to the doc site it will only reflect the current verstion and may not reflect the fixed version of nvd3 I'm using. 

Kind Thanks

**Comment by liquidpele** [comment]
Right now it's only current version, but that's because it generates the docs automatically based off of the actual nvd3 objects themselves... otherwise I would have used the wiki.   The benefit there is that you can then see what things dont' have descriptions, which was important when I was starting from zero.

**Comment by TroyLDay** [comment]
That is encouraging too...assuming that either a) there may be a versioning capability with the doc generator or b) I could regenerate the docs through my own build process with whatever version I'm using.

**Comment by liquidpele** [comment]
Well, when I say generated I mean it generates them on page view, in the javascript :p 

However, you can just checkout whatever version you want, and then view the docs... just open the index.html page in the repo when you clone it and checkout whatever version or branch you want to view.

**Comment by liquidpele** [comment]
Please open issues under novus/nvd3, thanks!
