### ISSUE TITLE
Data in docs

### ISSUE THREAD

**Issue by thany** [nvd3-community/nvd3#117]
It'd be greatly helpful to include in the docs what the data is suppposed to look like. Right now, we can only infer from examples, and broom together some of the attributes that can be supplied with a dataset (for example `strokeWidth`, apparently, which is found nowhere in the docs). And we have to guesstimate what nvd3 expects the overall structure of the data object to look like.

**Comment by liquidpele** [comment]
Please create issues/prs in the novus/nvd3 repo, thanks.

**Comment by liquidpele** [comment]
data attribute list is here:  https://github.com/novus/nvd3/wiki/Data-Attributes

Not complete, but feel free to add stuff you see is missing!

**Comment by thany** [comment]
But, the Github link on the documentation links to this repo... Why is that then?

**Comment by liquidpele** [comment]
Long story... basically because novus has pretty much abandoned it so I forked it... then they showed up and wanted to get control back and added me to their org.  I mostly agreed to it because they control nvd3.org which would inhibit my fork... so for now this org is just in case they boot me or something :)
