### ISSUE TITLE
How to run tests documented in nvd3 somewhere?

### ISSUE THREAD

**Issue by portante** [nvd3-community/nvd3#24]
Is the method of how to run unit tests for nvd3 documented somewhere?

I'd like to be able to run tests, but I get the following error:

```
$ grunt karma
Running "karma:unit" (karma) task
ERROR [launcher]: Cannot start Chrome
 
ERROR [launcher]: Cannot start Chrome
 
ERROR [launcher]: Cannot start Chrome
 
ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
 
 
 
Warning: Task "karma:unit" failed. Use --force to continue.
 
Aborted due to warnings.
```

**Comment by liquidpele** [comment]
I've yet to try and run the existing tests to be honest, perhaps someone who has before can chime in...

**Comment by liquidpele** [comment]
If you do get tests running, can you write up steps in the readme for others?

**Comment by inolasco** [comment]
I was able to run them, and here are the results:

    Chrome 39.0.2171 (Mac OS X 10.10.1): Executed 126 of 132 (30 FAILED) (skipped 6) (2.581 secs / 0.371 secs)

@portante You might have config issues with karma, which I probably don't have because I set it up for another project, though I can't recall what steps I did for that. I'll see if I can write the steps to make it work.

**Comment by inolasco** [comment]
I found myself unable to fork this repo, because I already had a fork of nvd3, which is very outdated, but I can't delete at the time. So I'll post here the steps I did to run tests, in markdown, which someone can copy to the readme:


<pre>
## Running tests

Install [Google Chrome](https://www.google.com/chrome/browser/desktop/index.html) if you don't have it already

Install node dependencies (grunt, karma, mocha, etc)

    npm install

Install bower dependencies (d3)

    bower install

Execute tests

    grunt karma


On Windows, you may need to set the `CHROME_BIN` environment variable to point to the Chrome executable

    CHROME_BIN='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'


</pre>

**Comment by portante** [comment]
@liquidpele, @inolasco, see PR #58 for a proposed solution.
