### ISSUE TITLE
Bug or problem with my code?

### ISSUE THREAD

**Issue by karassik** [nvd3-community/nvd3#26]
I can't seem to access the e.color element, which I am successfully doing in other pie graphs on the same page, so I know it works.  But the MultiBarChart graph doesn't seem to be able to access e.color as I have it below.
```javascript
var colors = ['#5f9e5f', '#269abc', '#d58512', '#d43f3a'];
nv.addGraph(function() {
    var chart = nv.models.multiBarChart()
        .stacked(true)
        .tooltips(true)
        .color(colors)
        .rotateLabels(-45)
        .tooltipContent(function(key, x, y, e, graph){
          return "<div>" + y + "</div><div style='color:" + e.color + "'>" + key + "</div><div>" + x + "</div>";
         });
    chart.yAxis.tickFormat(d3.format(',f'));

    d3.select('#test5')
        .datum(test_data)
        .transition().duration(1200)
        .call(chart);
    
    nv.utils.windowResize(chart.update);
    console.log('calling chart');
    // svg.transition().duration(0).call(chart);
    return chart;
});
```

**Comment by liquidpele** [comment]
IIRC, I added the color to be passed to the pie chart myself because I wanted to use it there... 

Different graphs pass different things to the tooltip too, it's not really standardized unfortunately, so there might be a way to get the color there but you'll probably want to do a console.log() on each of the things passed into the tooltip function to see what all they are.

**Comment by karassik** [comment]
Perfect.  I used e.series.color.  Thanks.
