### ISSUE TITLE
chart.yAxis.tickFormat for stackedAreaChart is broken

### ISSUE THREAD

**Issue by bochoven** [nvd3-community/nvd3#27]
I moved the issue from @jzipfler here.

With the new version, the tickFormat() for the yAxis seems to be broken.
I reproduced that with the following [jsFiddle](http://jsfiddle.net/LyvnLxmx/)

Additional information:

* The axisLabel() is applied.
* d3.format() and other approaches also not working.
* For xAxis everything is fine.
* I tried the same behaviour with a multiBarChart, and there it works.
* Have not tried other charts.

**Comment by Rrrapture** [comment]
I'm also getting this problem with tickFormat. It doesn't change from the default:
    var yAxisTickFormat = d3.format(',.2f')

**Comment by liquidpele** [comment]
Looking at the code, it seems you have to use the chart.yAxisTickFormat() option, not yAxis.tickFormat()

This is because the controls that change it between stacked/stream/expanded will change the y format to make sense for each type of display, so it has to keep track of the regular format independent of the axis.  Or at least that's how they wrote it... probably better ways to have done it but changing it now would probably break other people :/  

 I did change the example to use the correct call though:

https://github.com/nvd3-community/nvd3/commit/7fffa6a0a143eef9ce07887a449b189009cf5a88

**Comment by Rrrapture** [comment]
@liquidpele thank you! I was so tired I didn't think of passing the option that way.
