### ISSUE TITLE
Multibarchart with line chart?

### ISSUE THREAD

**Issue by dougmillerknd** [nvd3-community/nvd3#68]
Is it possible to have a multibarchart on the left y axis and a line chart on the right y axis?
This is possible with regular linePlusBarChart but the chart I am using compares positive and negative and I am trying to have a line showing the difference between them. See the image for reference.
![multichartwithline](https://cloud.githubusercontent.com/assets/7928931/6262762/892dade8-b855-11e4-9e02-2142890b025f.png)

Is there a way to do this currently? Is multichart the way to go (is quite complex)?

**Comment by liquidpele** [comment]
Hey there! I don't think this is currently possible because a multibar is really a discrete bar chart which uses an ordinal axis, and a line is a time series which uses a linear axis.  

https://github.com/mbostock/d3/wiki/Ordinal-Scales

https://github.com/mbostock/d3/wiki/Time-Scales

However, I *could* be wrong about that... you could probably hack up a multibar use a time scale like the historical bar does maybe?

**Comment by dougmillerknd** [comment]
Thanks for checking on this so quick. How is a linePlusBarChart working? Is it usinga linear axis for the bars there? Ideally I would want the same setup but with the negative component too.

**Comment by liquidpele** [comment]
linePlusBar's bars are based on historicalBar, which uses a linear x axis, that's why I mentioned historical  bar (see the historicalBar.js and historicalBarChart.js models).
